# Generated by Django 6.0 on 2025-12-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_studytimescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
